server:
  port: 9000
spring:
  datasource:
    username: root
    password: FD3XJwIqxrfI
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.33.251.122:3306/ys?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 101.33.251.122
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-wait: -1
    password: 9I9n6omRYr@q

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.quantacenter.server.pojo

jwt:
  tokenHeader: Authorization
  secret: ys-secret
  expiration: 604800
  tokenHead: Bearer

# 订单金额配置
orderAmount:
  levelOne: "500"
  levelTwo: "1000"

logging:
  level:
    com:
      quantacenter:
        mapper: debug